# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 172423d80e9b59fa36343419af8473900e49c267ca14a484c8ed69b80119536a7cd8b937d8b72a394f6fe1e7fcc0e2bfcc007fad45c6332b10c89791fd6b095d

test:
  secret_key_base: a7469c4e92792666e5020a152eb3e4ef30adde69783f6d3ec813846c56ab73a299f062943149931d8136d8e1eefaf83d191d8065d41a663f7498675e4d6c74ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
